name: DevSecOps-Machine-Scanner
on: [push]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Scans the entire commit history

      - name: Secret Scanner (TruffleHog)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: "" # Scan from the very first commit
          head: ${{ github.ref_name }}
          extra_args: --debug --only-verified=false