name: DevSecOps-Machine-Scanner
on: [push]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Scans the entire commit history

      - name: Secret Scanner (TruffleHog)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
          - name: Secret Scanner (TruffleHog)
        uses: trufflesecurity/trufflehog-github-action@main
        with:
          base: "" # This tells it to scan from the very beginning
          head: ${{ github.ref_name }}
          extra_args: --only-verified # Optional: filters for real hits